# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.

# Basic Site Settings
locale                   : "en-US"
site_theme               : "default" # Currently available options are "default", "air"
title                    : "Mikko Seppälä"
title_separator          : "-"
name                     : &name "Mikko Seppälä"
description              : &description "Personal webpage of Mikko Seppälä"   # Update this with a general description of your site, this is the default if not overridden by a page
url                      : https://miksepp.github.io
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "miksepp/miksepp.github.io"

# Site Author - The following control what appear as part of the author content on the side bar.
#               If a field is blank the icon and link will not appear, otherwise it will be shown.
#               Additional customization can be done by editing /_includes/author-profile.html
author:
  # Biographic information
  avatar           : "profile.png"
  name             : "Your Sidebar Name"
  pronouns         : # example: "she/her"  
  bio              : "Doctoral Researcher"
  location         : "Helsinki, Finland"
  employer         : "University of Helsinki & Helsinki Institute of Physics"
  uri              : # URL
  email            : "mikko.seppala@helsinki.fi" 

  # Academic websites
  academia         : # URL
  arxiv            : # URL - Update with the correct link to your profile
  googlescholar    : #
  inspire-hep      : # URL
  impactstory      : # URL
  orcid            : #
  semantic         : # URL
  pubmed           : #
  researchgate     : # URL
  scopus           : # URL


